name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  commit_info:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository (with fetch depth of 0 for full history)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This fetches the entire commit history, not just the latest commit

      # Step 2: Fetch commit details for the latest commit
      - name: Get Commit Information
        run: |
          echo "Fetching commit details..."

          # Show the most recent commit hash and message
          echo "Commit Hash: $(git log -1 --pretty=format:'%H')"
          echo "Commit Author: $(git log -1 --pretty=format:'%an')"
          echo "Commit Message: $(git log -1 --pretty=format:'%s')"

          # Optionally, show the last 3 commits
          echo "Last 3 commits:"
          git log -3 --pretty=format:"%H %an %s"

      # Step 3: Show files changed in the latest commit
      - name: Show files changed in the latest commit
        run: |
          echo "Files changed in the latest commit:"
          
          # List the names of files changed between the most recent commit and the previous one
          git diff --name-only HEAD^ HEAD  # Use HEAD^ (equivalent to HEAD~1) to compare with previous commit

      # Step 4: Show the actual changes (diffs) made in the latest commit
      - name: Show the diffs of the changes in the latest commit
        run: |
          echo "Showing actual changes (diffs) made in the latest commit..."
          
          # Show the diff (what was added or removed) between the latest commit and the previous commit
          git diff HEAD^ HEAD  # Use HEAD^ (equivalent to HEAD~1) to compare with previous commit

      # Optional: Add other tasks like testing or building your project
      - name: Run a multi-line script
        run: |
          echo "This is a simple CI pipeline!"
          echo "You can add steps to build, test, and deploy your project."